#!/bin/sh

node executor.js $(cat lastrun) > lastrun.log 2>&1
# https://stackoverflow.com/questions/16548528/command-to-get-time-in-milliseconds

STATUS=$?

if test $STATUS -eq 0
then
    echo $(($(date +%s%N)/1000000)) > lastrun
    date >> lastrun
fi

