#!/bin/sh

echo "Your current working dir is:"
pwd

printf "Enter the full path to the backup dir: "
read BDIR
printf "Enter the full path to the script dir: "
read SDIR
printf "Enter user name used for backup: " 
read USER
printf "Enter password used for backup: "
read PASS
printf "Enter which day of month should the backup take place (e.g. 3rd Friday of the month)."
printf "First value expected is the order: value from 1 to 4: " 
read WEEK
printf "The second value is the day of week (0=Sunday, 1=Monday, ..., 5=Friday, 6=Saturday): "
read WDAY

cp $SDIR/backup.template $SDIR/backup

# https://zhu45.org/posts/2016/Dec/21/environment-variable-substitution-using-sed/
sed -i 's|#BDIR#|'$BDIR'|g' $SDIR/backup
sed -i 's|#SDIR#|'$SDIR'|g' $SDIR/backup
sed -i 's|#USER#|'$USER'|g' $SDIR/backup
sed -i "s|#PASS#|$PASS|g" $SDIR/backup
sed -i "s|#WEEK#|$WEEK|g" $SDIR/backup
sed -i "s|#WDAY#|$WDAY|g" $SDIR/backup

chmod 755 $SDIR/backup

rm -f /etc/cron.daily/spider-traits-backup
ln -s $SDIR/backup /etc/cron.daily/spider-traits-backup

# create the initial full backup
$SDIR/backup full