TRUNCATE TABLE `country`;

INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Afghanistan','AF','AFG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Åland Islands','AX','ALA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Albania','AL','ALB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Algeria','DZ','DZA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('American Samoa','AS','ASM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Andorra','AD','AND');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Angola','AO','AGO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Anguilla','AI','AIA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Antarctica','AQ','ATA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Antigua and Barbuda','AG','ATG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Argentina','AR','ARG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Armenia','AM','ARM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Aruba','AW','ABW');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Australia','AU','AUS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Austria','AT','AUT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Azerbaijan','AZ','AZE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bahamas','BS','BHS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bahrain','BH','BHR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bangladesh','BD','BGD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Barbados','BB','BRB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Belarus','BY','BLR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Belgium','BE','BEL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Belize','BZ','BLZ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Benin','BJ','BEN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bermuda','BM','BMU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bhutan','BT','BTN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bolivia (Plurinational State of)','BO','BOL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bonaire, Sint Eustatius and Saba','BQ','BES');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bosnia and Herzegovina','BA','BIH');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Botswana','BW','BWA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bouvet Island','BV','BVT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Brazil','BR','BRA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('British Indian Ocean Territory','IO','IOT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Brunei Darussalam','BN','BRN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Bulgaria','BG','BGR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Burkina Faso','BF','BFA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Burundi','BI','BDI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cabo Verde','CV','CPV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cambodia','KH','KHM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cameroon','CM','CMR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Canada','CA','CAN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cayman Islands','KY','CYM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Central African Republic','CF','CAF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Chad','TD','TCD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Chile','CL','CHL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('China','CN','CHN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Christmas Island','CX','CXR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cocos (Keeling) Islands','CC','CCK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Colombia','CO','COL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Comoros','KM','COM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Congo','CG','COG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Congo, Democratic Republic of the','CD','COD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cook Islands','CK','COK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Costa Rica','CR','CRI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Côte d\'Ivoire','CI','CIV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Croatia','HR','HRV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cuba','CU','CUB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Curaçao','CW','CUW');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Cyprus','CY','CYP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Czechia','CZ','CZE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Denmark','DK','DNK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Djibouti','DJ','DJI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Dominica','DM','DMA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Dominican Republic','DO','DOM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Ecuador','EC','ECU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Egypt','EG','EGY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('El Salvador','SV','SLV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Equatorial Guinea','GQ','GNQ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Eritrea','ER','ERI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Estonia','EE','EST');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Eswatini','SZ','SWZ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Ethiopia','ET','ETH');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Falkland Islands (Malvinas)','FK','FLK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Faroe Islands','FO','FRO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Fiji','FJ','FJI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Finland','FI','FIN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('France','FR','FRA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('French Guiana','GF','GUF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('French Polynesia','PF','PYF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('French Southern Territories','TF','ATF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Gabon','GA','GAB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Gambia','GM','GMB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Georgia','GE','GEO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Germany','DE','DEU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Ghana','GH','GHA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Gibraltar','GI','GIB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Greece','GR','GRC');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Greenland','GL','GRL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Grenada','GD','GRD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guadeloupe','GP','GLP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guam','GU','GUM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guatemala','GT','GTM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guernsey','GG','GGY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guinea','GN','GIN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guinea-Bissau','GW','GNB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Guyana','GY','GUY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Haiti','HT','HTI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Heard Island and McDonald Islands','HM','HMD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Holy See','VA','VAT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Honduras','HN','HND');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Hong Kong','HK','HKG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Hungary','HU','HUN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Iceland','IS','ISL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('India','IN','IND');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Indonesia','ID','IDN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Iran (Islamic Republic of)','IR','IRN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Iraq','IQ','IRQ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Ireland','IE','IRL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Isle of Man','IM','IMN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Israel','IL','ISR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Italy','IT','ITA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Jamaica','JM','JAM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Japan','JP','JPN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Jersey','JE','JEY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Jordan','JO','JOR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Kazakhstan','KZ','KAZ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Kenya','KE','KEN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Kiribati','KI','KIR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Korea (Democratic People\'s Republic of)','KP','PRK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Korea, Republic of','KR','KOR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Kuwait','KW','KWT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Kyrgyzstan','KG','KGZ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Lao People\'s Democratic Republic','LA','LAO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Latvia','LV','LVA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Lebanon','LB','LBN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Lesotho','LS','LSO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Liberia','LR','LBR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Libya','LY','LBY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Liechtenstein','LI','LIE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Lithuania','LT','LTU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Luxembourg','LU','LUX');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Macao','MO','MAC');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Madagascar','MG','MDG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Malawi','MW','MWI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Malaysia','MY','MYS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Maldives','MV','MDV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mali','ML','MLI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Malta','MT','MLT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Marshall Islands','MH','MHL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Martinique','MQ','MTQ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mauritania','MR','MRT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mauritius','MU','MUS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mayotte','YT','MYT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mexico','MX','MEX');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Micronesia (Federated States of)','FM','FSM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Moldova, Republic of','MD','MDA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Monaco','MC','MCO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mongolia','MN','MNG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Montenegro','ME','MNE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Montserrat','MS','MSR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Morocco','MA','MAR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Mozambique','MZ','MOZ');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Myanmar','MM','MMR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Namibia','NA','NAM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Nauru','NR','NRU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Nepal','NP','NPL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Netherlands','NL','NLD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('New Caledonia','NC','NCL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('New Zealand','NZ','NZL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Nicaragua','NI','NIC');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Niger','NE','NER');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Nigeria','NG','NGA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Niue','NU','NIU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Norfolk Island','NF','NFK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('North Macedonia','MK','MKD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Northern Mariana Islands','MP','MNP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Norway','NO','NOR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Oman','OM','OMN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Pakistan','PK','PAK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Palau','PW','PLW');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Palestine, State of','PS','PSE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Panama','PA','PAN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Papua New Guinea','PG','PNG');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Paraguay','PY','PRY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Peru','PE','PER');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Philippines','PH','PHL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Pitcairn','PN','PCN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Poland','PL','POL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Portugal','PT','PRT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Puerto Rico','PR','PRI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Qatar','QA','QAT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Réunion','RE','REU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Romania','RO','ROU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Russian Federation','RU','RUS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Rwanda','RW','RWA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Barthélemy','BL','BLM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Helena, Ascension and Tristan da Cunha','SH','SHN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Kitts and Nevis','KN','KNA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Lucia','LC','LCA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Martin (French part)','MF','MAF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Pierre and Miquelon','PM','SPM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saint Vincent and the Grenadines','VC','VCT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Samoa','WS','WSM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('San Marino','SM','SMR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sao Tome and Principe','ST','STP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Saudi Arabia','SA','SAU');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Senegal','SN','SEN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Serbia','RS','SRB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Seychelles','SC','SYC');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sierra Leone','SL','SLE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Singapore','SG','SGP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sint Maarten (Dutch part)','SX','SXM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Slovakia','SK','SVK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Slovenia','SI','SVN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Solomon Islands','SB','SLB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Somalia','SO','SOM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('South Africa','ZA','ZAF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('South Georgia and the South Sandwich Islands','GS','SGS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('South Sudan','SS','SSD');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Spain','ES','ESP');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sri Lanka','LK','LKA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sudan','SD','SDN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Suriname','SR','SUR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Svalbard and Jan Mayen','SJ','SJM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Sweden','SE','SWE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Switzerland','CH','CHE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Syrian Arab Republic','SY','SYR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Taiwan, Province of China[a]','TW','TWN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tajikistan','TJ','TJK');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tanzania, United Republic of','TZ','TZA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Thailand','TH','THA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Timor-Leste','TL','TLS');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Togo','TG','TGO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tokelau','TK','TKL');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tonga','TO','TON');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Trinidad and Tobago','TT','TTO');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tunisia','TN','TUN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Turkey','TR','TUR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Turkmenistan','TM','TKM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Turks and Caicos Islands','TC','TCA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Tuvalu','TV','TUV');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Uganda','UG','UGA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Ukraine','UA','UKR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('United Arab Emirates','AE','ARE');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('United Kingdom of Great Britain and Northern Ireland','GB','GBR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('United States of America','US','USA');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('United States Minor Outlying Islands','UM','UMI');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Uruguay','UY','URY');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Uzbekistan','UZ','UZB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Vanuatu','VU','VUT');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Venezuela (Bolivarian Republic of)','VE','VEN');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Viet Nam','VN','VNM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Virgin Islands (British)','VG','VGB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Virgin Islands (U.S.)','VI','VIR');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Wallis and Futuna','WF','WLF');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Western Sahara','EH','ESH');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Yemen','YE','YEM');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Zambia','ZM','ZMB');
INSERT INTO `country` (`name`,`alpha2_code`,`alpha3_code`) VALUES ('Zimbabwe','ZW','ZWE');

INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Forest', '1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Boreal', '1.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest - Subarctic', '1.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subantarctic', '1.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Temperate', '1.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subtropical/tropical dry', '1.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subtropical/tropical moist lowland', '1.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subtropical/tropical mangrove vegetation above high tide level', '1.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subtropical/tropical swamp', '1.8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Forrest','Forest – Subtropical/tropical moist montane', '1.9');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Savanna', '2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Savana','Savanna - Dry', '2.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Savana','Savanna - Moist', '2.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Shrubland', '3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Subarctic', '3.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Subantarctic', '3.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Boreal', '3.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland –Temperate', '3.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Subtropical/tropical dry', '3.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Subtropical/tropical moist', '3.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Subtropical/tropical high altitude', '3.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Shrubland','Shrubland – Mediterranean-type shrubby vegetation', '3.8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Grassland', '4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Tundra', '4.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Subarctic', '4.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Subantarctic', '4.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Temperate', '4.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Subtropical/tropical dry', '4.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Subtropical/tropical seasonally wet/flooded', '4.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Grassland','Grassland – Subtropical/tropical high altitude', '4.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Wetlands (inland)', '5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent rivers/streams/creeks (includes waterfalls)', '5.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Seasonal/intermittent/irregular rivers/streams/creeks', '5.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Shrub dominated wetlands', '5.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Bogs, marshes, swamps, fens, peatlands', '5.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent freshwater lakes (over 8 ha)', '5.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Seasonal/intermittent freshwater lakes (over 8 ha)', '5.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent freshwater marshes/pools (under 8 ha)', '5.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Seasonal/intermittent freshwater marshes/pools (under 8 ha)', '5.8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Freshwater springs and oases', '5.9');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Tundra wetlands (inc. pools and temporary waters from snowmelt)', '5.10');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Alpine wetlands (inc. temporary waters from snowmelt)', '5.11');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Geothermal wetlands', '5.12');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent inland deltas', '5.13');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent saline, brackish or alkaline lakes', '5.14');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Seasonal/intermittent saline, brackish or alkaline lakes and flats', '5.15');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Permanent saline, brackish or alkaline marshes/pools', '5.16');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Seasonal/intermittent saline, brackish or alkaline marshes/pools', '5.17');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Wetlands (inland)','Wetlands (inland) – Karst and other subterranean hydrological systems (inland)', '5.18');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Rocky Areas (e.g., inland cliffs, mountain peaks)', '6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Caves & Subterranean Habitats (non-aquatic)', '7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Caves & Subterranean Habitats (non-aquatic)','Caves and Subterranean Habitats (non-aquatic) – Caves', '7.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Caves & Subterranean Habitats (non-aquatic)','Caves and Subterranean Habitats (non-aquatic) – Other subterranean habitats', '7.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Desert', '8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Desert','Desert – Hot', '8.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Desert','Desert – Temperate', '8.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Desert','Desert – Cold', '8.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Marine Neritic', '9');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Pelagic', '9.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Subtidal rock and rocky reefs', '9.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Subtidal loose rock/pebble/gravel', '9.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Subtidal sandy', '9.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Subtidal sandy-mud', '9.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Subtidal muddy', '9.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Macroalgal/kelp', '9.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Marine Neritic – Coral Reef', '9.8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Outer reef channel', '9.8.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Back slope', '9.8.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Foreslope (outer reef slope)', '9.8.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Lagoon', '9.8.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Inter-reef soft substrate', '9.8.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Inter-reef rubble substrate', '9.8.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Seagrass (Submerged)', '9.9');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Neritic','Estuaries', '9.10');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Marine Oceanic', '10');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Oceanic','Epipelagic (0–200 m)', '10.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Oceanic','Mesopelagic (200–1,000 m)', '10.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Oceanic','Bathypelagic (1,000–4,000 m)', '10.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Oceanic','Abyssopelagic (4,000–6,000 m)', '10.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Marine Deep Ocean Floor (Benthic and Demersal)', '11');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Continental Slope/Bathyl Zone (200–4,000 m)', '11.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Hard Substrate', '11.1.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Soft Substrate', '11.1.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Abyssal Plain (4,000–6,000 m)', '11.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Abyssal Mountain/Hills (4,000–6,000 m)', '11.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Hadal/Deep Sea Trench (>6,000 m)', '11.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Seamount', '11.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Deep Ocean Floor (Benthic and Demersal)','Deep Sea Vents (Rifts/Seeps)', '11.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Marine Intertidal', '12');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Rocky Shoreline', '12.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Sandy Shoreline and/or Beaches, Sand Bars, Spits, etc.', '12.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Shingle and/or Pebble Shoreline and/or Beaches', '12.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Mud Shoreline and Intertidal Mud Flats', '12.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Salt Marshes (Emergent Grasses)', '12.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Tidepools', '12.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Intertidal','Mangrove Submerged Roots', '12.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Marine Coastal/Supratidal', '13');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Coastal/Supratidal','Sea Cliffs and Rocky Offshore Islands', '13.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Coastal/Supratidal','Coastal Caves/Karst', '13.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Coastal/Supratidal','Coastal Sand Dunes', '13.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Coastal/Supratidal','Coastal Brackish/Saline Lagoons/Marine Lakes', '13.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Marine Coastal/Supratidal','Coastal Freshwater Lakes', '13.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Artificial - Terrestrial', '14');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Arable Land', '14.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Pastureland', '14.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Plantations', '14.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Rural Gardens', '14.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Urban Areas', '14.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Terrestrial','Subtropical/Tropical Heavily Degraded Former Forest', '14.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Artificial - Aquatic', '15');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Water Storage Areas [over 8 ha]', '15.1');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Ponds [below 8 ha]', '15.2');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Aquaculture Ponds', '15.3');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Salt Exploitation Sites', '15.4');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Excavations (open)', '15.5');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Wastewater Treatment Areas', '15.6');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Irrigated Land [includes irrigation channels]', '15.7');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Seasonally Flooded Agricultural Land', '15.8');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Canals and Drainage Channels, Ditches', '15.9');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Karst and Other Subterranean Hydrological Systems [human-made]', '15.10');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Marine Anthropogenic Structures', '15.11');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Mariculture Cages', '15.12');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES ('Artificial - Aquatic','Mari/Brackish-culture Ponds', '15.13');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Introduced Vegetation', '16');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Other', '17');
INSERT INTO `habitat_global` (`category`, `name`, `number`) VALUES (NULL,'Unknown', '18');

